export const edificiosSeed = [
  { codigo: 'A', nombre: 'Modulo A - Auditorio Enrique Diaz de Leon', tipo: 'EDIFICIO_ACADEMICO', zona: 'SUR', centroidX: 16, centroidY: 43, boundingBox: [{ x: 12, y: 39 }, { x: 20, y: 39 }, { x: 20, y: 47 }, { x: 12, y: 47 }] },
  { codigo: 'B', nombre: 'Modulo B', tipo: 'EDIFICIO_ACADEMICO', zona: 'SUR', centroidX: 33, centroidY: 43, boundingBox: [{ x: 31, y: 42 }, { x: 35, y: 42 }, { x: 35, y: 44 }, { x: 31, y: 44 }] },
  { codigo: 'C', nombre: 'Modulo C', tipo: 'EDIFICIO_ACADEMICO', zona: 'SUR', centroidX: 32, centroidY: 41, boundingBox: [{ x: 30, y: 40 }, { x: 34, y: 40 }, { x: 34, y: 42 }, { x: 30, y: 42 }] },
  { codigo: 'D', nombre: 'Modulo D', tipo: 'EDIFICIO_ACADEMICO', zona: 'SUR', centroidX: 29, centroidY: 39, boundingBox: [{ x: 27, y: 38 }, { x: 32, y: 38 }, { x: 32, y: 40 }, { x: 27, y: 40 }] },
  { codigo: 'E', nombre: 'Modulo E', tipo: 'EDIFICIO_ACADEMICO', zona: 'CENTRAL', centroidX: 22, centroidY: 32, boundingBox: [{ x: 14, y: 31 }, { x: 30, y: 31 }, { x: 30, y: 33 }, { x: 14, y: 33 }] },
  {
    codigo: 'F',
    nombre: 'Modulo F - Multi-ala',
    tipo: 'EDIFICIO_ACADEMICO',
    zona: 'CENTRAL',
    centroidX: 23,
    centroidY: 28,
    boundingBox: [
      { x: 18, y: 23 },
      { x: 24, y: 23 },
      { x: 24, y: 25 },
      { x: 29, y: 25 },
      { x: 29, y: 28 },
      { x: 24, y: 28 },
      { x: 24, y: 33 },
      { x: 20, y: 33 },
      { x: 20, y: 28 },
      { x: 18, y: 28 },
    ],
  },
  { codigo: 'G', nombre: 'Modulo G', tipo: 'EDIFICIO_ACADEMICO', zona: 'SUR', centroidX: 13, centroidY: 29, boundingBox: [{ x: 11, y: 27 }, { x: 15, y: 27 }, { x: 15, y: 30 }, { x: 11, y: 30 }] },
  { codigo: 'H', nombre: 'Modulo H', tipo: 'EDIFICIO_ACADEMICO', zona: 'CENTRAL', centroidX: 18, centroidY: 27, boundingBox: [{ x: 17, y: 26 }, { x: 19, y: 26 }, { x: 19, y: 28 }, { x: 17, y: 28 }] },
  { codigo: 'I', nombre: 'Modulo I', tipo: 'EDIFICIO_ACADEMICO', zona: 'CENTRAL', centroidX: 27, centroidY: 29, boundingBox: [{ x: 25, y: 28 }, { x: 30, y: 28 }, { x: 30, y: 30 }, { x: 25, y: 30 }] },
  { codigo: 'J', nombre: 'Modulo J', tipo: 'EDIFICIO_ACADEMICO', zona: 'CENTRAL', centroidX: 23, centroidY: 22, boundingBox: [{ x: 21, y: 21 }, { x: 24, y: 21 }, { x: 24, y: 23 }, { x: 21, y: 23 }] },
  { codigo: 'K', nombre: 'Modulo K', tipo: 'EDIFICIO_ACADEMICO', zona: 'CENTRAL', centroidX: 22, centroidY: 20, boundingBox: [{ x: 20, y: 19 }, { x: 25, y: 19 }, { x: 25, y: 21 }, { x: 20, y: 21 }] },
  { codigo: 'L', nombre: 'Modulo L', tipo: 'SERVICIO', zona: 'ESTE_NORESTE', centroidX: 30, centroidY: 20, boundingBox: [{ x: 27, y: 17 }, { x: 32, y: 17 }, { x: 32, y: 23 }, { x: 27, y: 23 }] },
  { codigo: 'M', nombre: 'Modulo M', tipo: 'EDIFICIO_ACADEMICO', zona: 'CENTRAL', centroidX: 20, centroidY: 18, boundingBox: [{ x: 19, y: 17 }, { x: 22, y: 17 }, { x: 22, y: 19 }, { x: 19, y: 19 }] },
  { codigo: 'N', nombre: 'Modulo N', tipo: 'EDIFICIO_ACADEMICO', zona: 'CENTRAL', centroidX: 20, centroidY: 16, boundingBox: [{ x: 18, y: 15 }, { x: 22, y: 15 }, { x: 22, y: 17 }, { x: 18, y: 17 }] },
  { codigo: 'O', nombre: 'Modulo O', tipo: 'EDIFICIO_ACADEMICO', zona: 'CENTRAL', centroidX: 19, centroidY: 13, boundingBox: [{ x: 17, y: 11 }, { x: 22, y: 11 }, { x: 22, y: 15 }, { x: 17, y: 15 }] },
  { codigo: 'P', nombre: 'Modulo P', tipo: 'EDIFICIO_ACADEMICO', zona: 'ESTE_NORESTE', centroidX: 29, centroidY: 13, boundingBox: [{ x: 25, y: 12 }, { x: 33, y: 12 }, { x: 33, y: 14 }, { x: 25, y: 14 }] },
  { codigo: 'Q', nombre: 'Modulo Q', tipo: 'EDIFICIO_ACADEMICO', zona: 'ESTE_NORESTE', centroidX: 32, centroidY: 11, boundingBox: [{ x: 28, y: 9 }, { x: 36, y: 9 }, { x: 36, y: 11 }, { x: 28, y: 11 }] },
  { codigo: 'R', nombre: 'Modulo R', tipo: 'EDIFICIO_ACADEMICO', zona: 'ESTE_NORESTE', centroidX: 26, centroidY: 11, boundingBox: [{ x: 24, y: 10 }, { x: 28, y: 10 }, { x: 28, y: 12 }, { x: 24, y: 12 }] },
  { codigo: 'S', nombre: 'Modulo S', tipo: 'EDIFICIO_ACADEMICO', zona: 'CENTRAL', centroidX: 21, centroidY: 11, boundingBox: [{ x: 19, y: 10 }, { x: 23, y: 10 }, { x: 23, y: 12 }, { x: 19, y: 12 }] },
  { codigo: 'T', nombre: 'Modulo T', tipo: 'EDIFICIO_ACADEMICO', zona: 'ESTE_NORESTE', centroidX: 28, centroidY: 8, boundingBox: [{ x: 26, y: 8 }, { x: 31, y: 8 }, { x: 31, y: 9 }, { x: 26, y: 9 }] },
  { codigo: 'U', nombre: 'Modulo U', tipo: 'EDIFICIO_ACADEMICO', zona: 'ESTE_NORESTE', centroidX: 30, centroidY: 7, boundingBox: [{ x: 26, y: 6 }, { x: 33, y: 6 }, { x: 33, y: 7 }, { x: 26, y: 7 }] },
  { codigo: 'V', nombre: 'Modulo V', tipo: 'EDIFICIO_ACADEMICO', zona: 'NOROESTE', centroidX: 22, centroidY: 5, boundingBox: [{ x: 19, y: 4 }, { x: 24, y: 4 }, { x: 24, y: 5 }, { x: 19, y: 5 }] },
  { codigo: 'V2', nombre: 'Modulo V2', tipo: 'EDIFICIO_ACADEMICO', zona: 'NOROESTE', centroidX: 23, centroidY: 7, boundingBox: [{ x: 21, y: 6 }, { x: 25, y: 6 }, { x: 25, y: 7 }, { x: 21, y: 7 }] },
  { codigo: 'W', nombre: 'Modulo W', tipo: 'EDIFICIO_ACADEMICO', zona: 'NOROESTE', centroidX: 19, centroidY: 6, boundingBox: [{ x: 17, y: 6 }, { x: 21, y: 6 }, { x: 21, y: 7 }, { x: 17, y: 7 }] },
  { codigo: 'X', nombre: 'Modulo X', tipo: 'EDIFICIO_ACADEMICO', zona: 'NOROESTE', centroidX: 20, centroidY: 4, boundingBox: [{ x: 16, y: 4 }, { x: 24, y: 4 }, { x: 24, y: 5 }, { x: 16, y: 5 }] },
  {
    codigo: 'Y',
    nombre: 'Modulo Y - Laboratorios de ciencias basicas',
    tipo: 'EDIFICIO_ACADEMICO',
    zona: 'NOROESTE',
    centroidX: 10,
    centroidY: 14,
    boundingBox: [
      { x: 6, y: 11 },
      { x: 15, y: 11 },
      { x: 15, y: 13 },
      { x: 12, y: 13 },
      { x: 12, y: 18 },
      { x: 9, y: 18 },
      { x: 9, y: 13 },
      { x: 6, y: 13 },
    ],
  },
  { codigo: 'Z', nombre: 'Modulo Z', tipo: 'EDIFICIO_ACADEMICO', zona: 'NOROESTE', centroidX: 7, centroidY: 14, boundingBox: [{ x: 6, y: 13 }, { x: 8, y: 13 }, { x: 8, y: 16 }, { x: 6, y: 16 }] },
  { codigo: 'Z1', nombre: 'Modulo Z1', tipo: 'EDIFICIO_ACADEMICO', zona: 'NOROESTE', centroidX: 6, centroidY: 13, boundingBox: [{ x: 5, y: 12 }, { x: 7, y: 12 }, { x: 7, y: 14 }, { x: 5, y: 14 }] },
  { codigo: 'Z2', nombre: 'Modulo Z2', tipo: 'EDIFICIO_ACADEMICO', zona: 'NOROESTE', centroidX: 8, centroidY: 11, boundingBox: [{ x: 7, y: 10 }, { x: 9, y: 10 }, { x: 9, y: 12 }, { x: 7, y: 12 }] },
  { codigo: 'CID', nombre: 'Centro de Innovacion y Diseno (CID)', tipo: 'ZONA_CLAVE', zona: 'SUR', centroidX: 26, centroidY: 35, boundingBox: [{ x: 24, y: 33 }, { x: 29, y: 33 }, { x: 29, y: 37 }, { x: 24, y: 37 }] },
  { codigo: 'CO', nombre: 'Coliseo Olimpico', tipo: 'INSTALACION_DEPORTIVA', zona: 'ESTE_NORESTE', centroidX: 36, centroidY: 6, boundingBox: [{ x: 33, y: 4 }, { x: 40, y: 4 }, { x: 40, y: 8 }, { x: 33, y: 8 }] },
  { codigo: 'PA', nombre: 'Pista de Atletismo', tipo: 'INSTALACION_DEPORTIVA', zona: 'DEPORTIVA', centroidX: 43, centroidY: 28, boundingBox: [{ x: 39, y: 20 }, { x: 49, y: 20 }, { x: 49, y: 36 }, { x: 39, y: 36 }] },
];

export const campusAreasSeed = [
  {
    codigo: 'PERIMETRO_CUCEI',
    nombre: 'Perimetro campus CUCEI',
    tipo: 'PERIMETRO_CAMPUS',
    centroidX: 24,
    centroidY: 24,
    boundingBox: [
      { x: 4, y: 46 },
      { x: 2, y: 34 },
      { x: 3, y: 22 },
      { x: 4, y: 10 },
      { x: 7, y: 4 },
      { x: 18, y: 2 },
      { x: 34, y: 2 },
      { x: 42, y: 5 },
      { x: 47, y: 16 },
      { x: 48, y: 30 },
      { x: 44, y: 40 },
      { x: 36, y: 46 },
      { x: 20, y: 47 },
      { x: 9, y: 47 },
    ],
  },
  {
    codigo: 'JARDIN_CENTRAL',
    nombre: 'Jardin central CUCEI',
    tipo: 'JARDIN',
    centroidX: 23,
    centroidY: 24,
    boundingBox: [{ x: 17, y: 20 }, { x: 30, y: 20 }, { x: 30, y: 28 }, { x: 17, y: 28 }],
  },
  {
    codigo: 'JARDIN_NORTE',
    nombre: 'Jardin norte y letras CUCEI',
    tipo: 'JARDIN',
    centroidX: 14,
    centroidY: 10,
    boundingBox: [{ x: 8, y: 7 }, { x: 20, y: 7 }, { x: 20, y: 14 }, { x: 8, y: 14 }],
  },
  {
    codigo: 'EXPLANADA_SUR',
    nombre: 'Explanada sur acceso principal',
    tipo: 'EXPLANADA',
    centroidX: 24,
    centroidY: 39,
    boundingBox: [{ x: 18, y: 36 }, { x: 31, y: 36 }, { x: 31, y: 42 }, { x: 18, y: 42 }],
  },
  {
    codigo: 'PASILLOS_VERDES',
    nombre: 'Pasillos peatonales principales',
    tipo: 'PASILLO_PEATONAL',
    centroidX: 24,
    centroidY: 20,
    boundingBox: [{ x: 7, y: 5 }, { x: 41, y: 5 }, { x: 41, y: 33 }, { x: 7, y: 33 }],
  },
  {
    codigo: 'DEPORTIVA',
    nombre: 'Area deportiva pista y canchas',
    tipo: 'AREA_DEPORTIVA',
    centroidX: 43,
    centroidY: 28,
    boundingBox: [{ x: 37, y: 18 }, { x: 50, y: 18 }, { x: 50, y: 38 }, { x: 37, y: 38 }],
  },
  {
    codigo: 'ESTACIONAMIENTO_ORIENTE',
    nombre: 'Estacionamiento oriente',
    tipo: 'ESTACIONAMIENTO',
    centroidX: 36,
    centroidY: 16,
    boundingBox: [{ x: 33, y: 12 }, { x: 39, y: 12 }, { x: 39, y: 20 }, { x: 33, y: 20 }],
  },
];

export const pathNodesSeed = [
  { key: 'N1', coordX: 10, coordY: 6 },
  { key: 'N2', coordX: 16, coordY: 6 },
  { key: 'N3', coordX: 22, coordY: 6 },
  { key: 'N4', coordX: 28, coordY: 6 },
  { key: 'N5', coordX: 34, coordY: 6 },
  { key: 'N6', coordX: 40, coordY: 6 },

  { key: 'C1', coordX: 8, coordY: 18 },
  { key: 'C2', coordX: 14, coordY: 18 },
  { key: 'C3', coordX: 20, coordY: 18 },
  { key: 'C4', coordX: 26, coordY: 18 },
  { key: 'C5', coordX: 32, coordY: 18 },
  { key: 'C6', coordX: 38, coordY: 18 },

  { key: 'S1', coordX: 10, coordY: 32 },
  { key: 'S2', coordX: 16, coordY: 32 },
  { key: 'S3', coordX: 22, coordY: 32 },
  { key: 'S4', coordX: 28, coordY: 32 },
  { key: 'S5', coordX: 34, coordY: 32 },
  { key: 'S6', coordX: 40, coordY: 32 },

  { key: 'E1', coordX: 40, coordY: 4 },
  { key: 'E2', coordX: 40, coordY: 10 },
  { key: 'E3', coordX: 40, coordY: 16 },
  { key: 'E4', coordX: 40, coordY: 22 },
  { key: 'E5', coordX: 40, coordY: 28 },
  { key: 'E6', coordX: 40, coordY: 34 },

  { key: 'W1', coordX: 8, coordY: 12 },
  { key: 'W2', coordX: 8, coordY: 24 },
  { key: 'W3', coordX: 8, coordY: 30 },

  { key: 'A_ENT', coordX: 16, coordY: 39 },
  { key: 'CID_ENT', coordX: 26, coordY: 36 },
  { key: 'F_ENT', coordX: 23, coordY: 24 },
  { key: 'Y_ENT', coordX: 10, coordY: 14 },
  { key: 'CO_ENT', coordX: 34, coordY: 7 },
  { key: 'PA_ENT', coordX: 39, coordY: 27 },
  { key: 'Q_ENT', coordX: 32, coordY: 10 },
  { key: 'L_ENT', coordX: 30, coordY: 20 },
  { key: 'P_ENT', coordX: 28, coordY: 14 },
  { key: 'ZONA_Z_ENT', coordX: 7, coordY: 14 },
  { key: 'SUR_GATE', coordX: 14, coordY: 44 },
  { key: 'NORTE_GATE', coordX: 36, coordY: 3 },
  { key: 'ESTE_GATE', coordX: 45, coordY: 8 },
];

export const pathEdgesSeed = [
  ['N1', 'N2'], ['N2', 'N3'], ['N3', 'N4'], ['N4', 'N5'], ['N5', 'N6'],
  ['C1', 'C2'], ['C2', 'C3'], ['C3', 'C4'], ['C4', 'C5'], ['C5', 'C6'],
  ['S1', 'S2'], ['S2', 'S3'], ['S3', 'S4'], ['S4', 'S5'], ['S5', 'S6'],

  ['E1', 'E2'], ['E2', 'E3'], ['E3', 'E4'], ['E4', 'E5'], ['E5', 'E6'],

  ['W1', 'C1'], ['C1', 'W2'], ['W2', 'W3'],

  ['N6', 'E1'], ['C6', 'E3'], ['S6', 'E6'],
  ['N1', 'W1'], ['C1', 'W2'], ['S1', 'W3'],

  ['C3', 'F_ENT'], ['S3', 'A_ENT'], ['S4', 'CID_ENT'],
  ['N2', 'Y_ENT'], ['N5', 'Q_ENT'], ['C5', 'L_ENT'],
  ['N5', 'CO_ENT'], ['E5', 'PA_ENT'], ['C4', 'P_ENT'],
  ['C1', 'ZONA_Z_ENT'],

  ['S2', 'SUR_GATE'], ['N6', 'NORTE_GATE'], ['E2', 'ESTE_GATE'],
];

export const campusAssetsSeed = [
  { tipo: 'ARBOL', nombre: 'Arbol Norte 1', coordX: 12, coordY: 8, areaCodigo: 'JARDIN_NORTE' },
  { tipo: 'ARBOL', nombre: 'Arbol Norte 2', coordX: 15, coordY: 9, areaCodigo: 'JARDIN_NORTE' },
  { tipo: 'ARBOL', nombre: 'Arbol Norte 3', coordX: 17, coordY: 10, areaCodigo: 'JARDIN_NORTE' },
  { tipo: 'ARBOL', nombre: 'Arbol Central 1', coordX: 20, coordY: 23, areaCodigo: 'JARDIN_CENTRAL' },
  { tipo: 'ARBOL', nombre: 'Arbol Central 2', coordX: 24, coordY: 24, areaCodigo: 'JARDIN_CENTRAL' },
  { tipo: 'ARBOL', nombre: 'Arbol Central 3', coordX: 28, coordY: 25, areaCodigo: 'JARDIN_CENTRAL' },
  { tipo: 'ARBOL', nombre: 'Arbol Oriente 1', coordX: 35, coordY: 14, areaCodigo: 'ESTACIONAMIENTO_ORIENTE' },
  { tipo: 'ARBOL', nombre: 'Arbol Oriente 2', coordX: 36, coordY: 17, areaCodigo: 'ESTACIONAMIENTO_ORIENTE' },

  { tipo: 'ARBUSTO', nombre: 'Arbusto Norte', coordX: 10, coordY: 11, areaCodigo: 'JARDIN_NORTE' },
  { tipo: 'ARBUSTO', nombre: 'Arbusto Centro 1', coordX: 22, coordY: 26, areaCodigo: 'JARDIN_CENTRAL' },
  { tipo: 'ARBUSTO', nombre: 'Arbusto Centro 2', coordX: 25, coordY: 22, areaCodigo: 'JARDIN_CENTRAL' },

  { tipo: 'BANCA', nombre: 'Banca F Sur', coordX: 22, coordY: 30, areaCodigo: 'JARDIN_CENTRAL', orientacionDeg: 180 },
  { tipo: 'BANCA', nombre: 'Banca Letras', coordX: 12, coordY: 12, areaCodigo: 'JARDIN_NORTE', orientacionDeg: 90 },
  { tipo: 'BANCA', nombre: 'Banca CID', coordX: 27, coordY: 35, areaCodigo: 'EXPLANADA_SUR', orientacionDeg: 45 },
  { tipo: 'BANCA', nombre: 'Banca L', coordX: 30, coordY: 22, areaCodigo: 'PASILLOS_VERDES', orientacionDeg: 270 },

  { tipo: 'LUMINARIA', nombre: 'Luminaria N1', coordX: 20, coordY: 6, areaCodigo: 'PASILLOS_VERDES' },
  { tipo: 'LUMINARIA', nombre: 'Luminaria N2', coordX: 28, coordY: 6, areaCodigo: 'PASILLOS_VERDES' },
  { tipo: 'LUMINARIA', nombre: 'Luminaria C1', coordX: 20, coordY: 18, areaCodigo: 'PASILLOS_VERDES' },
  { tipo: 'LUMINARIA', nombre: 'Luminaria C2', coordX: 32, coordY: 18, areaCodigo: 'PASILLOS_VERDES' },
  { tipo: 'LUMINARIA', nombre: 'Luminaria S1', coordX: 22, coordY: 32, areaCodigo: 'PASILLOS_VERDES' },
  { tipo: 'LUMINARIA', nombre: 'Luminaria S2', coordX: 34, coordY: 32, areaCodigo: 'PASILLOS_VERDES' },

  { tipo: 'BASURERO', nombre: 'Basurero F', coordX: 24, coordY: 29, areaCodigo: 'JARDIN_CENTRAL' },
  { tipo: 'BASURERO', nombre: 'Basurero Y', coordX: 10, coordY: 15, areaCodigo: 'JARDIN_NORTE' },
  { tipo: 'BASURERO', nombre: 'Basurero L', coordX: 31, coordY: 20, areaCodigo: 'PASILLOS_VERDES' },
  { tipo: 'BASURERO', nombre: 'Basurero CID', coordX: 26, coordY: 34, areaCodigo: 'EXPLANADA_SUR' },
];
