export const puntosInteresSeed = [
  {
    nombre: 'Servicio Medico CUCEI',
    tipo: 'MEDICAL',
    coordenadaXGrid: 18,
    coordenadaYGrid: 27,
    descripcion: 'Modulo medico del campus para atencion rapida del MVP.',
    activo: true,
    edificioReferencia: 'H',
    prioridadVisual: 100,
  },
  {
    nombre: 'Banos Alfa',
    tipo: 'BATHROOM',
    coordenadaXGrid: 30,
    coordenadaYGrid: 19,
    descripcion: 'Banos cercanos al bloque Alfa y Beta.',
    activo: true,
    edificioReferencia: 'L',
    prioridadVisual: 88,
  },
  {
    nombre: 'Banos Beta',
    tipo: 'BATHROOM',
    coordenadaXGrid: 29,
    coordenadaYGrid: 20,
    descripcion: 'Segundo punto de banos para pruebas de filtros visuales.',
    activo: true,
    edificioReferencia: 'L',
    prioridadVisual: 87,
  },
  {
    nombre: 'CTA Cafeteria',
    tipo: 'CAFETERIA',
    coordenadaXGrid: 31,
    coordenadaYGrid: 18,
    descripcion: 'Cafeteria principal junto al CTA.',
    activo: true,
    edificioReferencia: 'L',
    prioridadVisual: 95,
  },
  {
    nombre: 'Puesto de Comida Central',
    tipo: 'FOOD',
    coordenadaXGrid: 28,
    coordenadaYGrid: 13,
    descripcion: 'Puesto rapido de alimentos para el corredor central.',
    activo: true,
    edificioReferencia: 'P',
    prioridadVisual: 80,
  },
  {
    nombre: 'Servicios Generales Oriente',
    tipo: 'GENERAL_SERVICES',
    coordenadaXGrid: 34,
    coordenadaYGrid: 14,
    descripcion: 'Modulo operativo de servicios generales del lado oriente.',
    activo: true,
    edificioReferencia: 'Q',
    prioridadVisual: 86,
  },
  {
    nombre: 'Cajero Santander CID',
    tipo: 'BANK',
    coordenadaXGrid: 26,
    coordenadaYGrid: 35,
    descripcion: 'Cajero ubicado en la zona del CID.',
    activo: true,
    edificioReferencia: 'D',
    prioridadVisual: 82,
  },
  {
    nombre: 'Auditorio Matute Remus',
    tipo: 'AUDITORIUM',
    coordenadaXGrid: 24,
    coordenadaYGrid: 18,
    descripcion: 'Auditorio para eventos y pruebas de navegacion del avatar.',
    activo: true,
    edificioReferencia: 'L',
    prioridadVisual: 83,
  },
  {
    nombre: 'Auditorio Antonio Rodriguez',
    tipo: 'AUDITORIUM',
    coordenadaXGrid: 11,
    coordenadaYGrid: 31,
    descripcion: 'Auditorio ubicado en el corredor sur poniente.',
    activo: true,
    edificioReferencia: 'G',
    prioridadVisual: 78,
  },
  {
    nombre: 'Auditorio Dr. Nikolai V. M',
    tipo: 'AUDITORIUM',
    coordenadaXGrid: 8,
    coordenadaYGrid: 12,
    descripcion: 'Auditorio de la zona occidental del campus.',
    activo: true,
    edificioReferencia: 'Z2',
    prioridadVisual: 79,
  },
  {
    nombre: 'Registro Escolar',
    tipo: 'INFO',
    coordenadaXGrid: 14,
    coordenadaYGrid: 45,
    descripcion: 'Punto informativo y de acceso para tramites escolares.',
    activo: true,
    edificioReferencia: 'A',
    prioridadVisual: 94,
  },
  {
    nombre: 'Control Escolar',
    tipo: 'ADMIN',
    coordenadaXGrid: 15,
    coordenadaYGrid: 46,
    descripcion: 'Modulo administrativo de control escolar.',
    activo: true,
    edificioReferencia: 'A',
    prioridadVisual: 91,
  },
  {
    nombre: 'Modulo de Informacion CID',
    tipo: 'INFO',
    coordenadaXGrid: 25,
    coordenadaYGrid: 34,
    descripcion: 'Punto de informacion para la zona del CID.',
    activo: true,
    edificioReferencia: 'D',
    prioridadVisual: 81,
  },
  {
    nombre: 'Lonaria Zona Oeste',
    tipo: 'FOOD',
    coordenadaXGrid: 6,
    coordenadaYGrid: 11,
    descripcion: 'Puesto de alimentos y snacks de la zona oeste.',
    activo: true,
    edificioReferencia: 'Z1',
    prioridadVisual: 74,
  },
];